table dim_order_payments
	lineageTag: d7accf2b-63d4-469d-a36f-280ac344c34b

	column order_id
		dataType: string
		lineageTag: 7f292fa2-4770-4a38-b573-2f66cffddd73
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: a79e5e9d-71fb-49a7-8fb5-dcfe0685be2f
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 28960cae-26fd-446e-95db-6b58103bbae5
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 69447fd2-2802-4dc5-b4fe-28d76488eb4c
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: decimal
		formatString: 0
		lineageTag: ff9c8166-b1f1-4298-a803-a147a79e0ff0
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

	partition dim_order_payments = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Csv.Document(File.Contents(Source & "order_payments.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

