table dim_customers
	lineageTag: 4a781a2d-9acc-4a36-b5b0-2170f221762b

	column customer_id
		dataType: string
		lineageTag: d170cea4-c5bb-40df-a849-3c67ed58c3fb
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: df4ba0d0-ceee-45a6-90eb-0f82737f1ebe
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column geolocation_lat
		dataType: string
		lineageTag: 9dc19446-5c2b-437c-a52b-64345077500d
		summarizeBy: none
		sourceColumn: geolocation_lat

		annotation SummarizationSetBy = Automatic

	column geolocation_lng
		dataType: string
		lineageTag: a086a856-40b9-40ed-83a7-ed919de62c61
		summarizeBy: none
		sourceColumn: geolocation_lng

		annotation SummarizationSetBy = Automatic

	column geolocation_city
		dataType: string
		lineageTag: 6d5e9798-5543-4ebb-9be8-b9f0aac92dcd
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: 591d272c-b78d-4383-bf28-270ab803ecd7
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: string
		lineageTag: 178917f0-c812-4506-b85b-c8663aba9a85
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\amanda.santos_corebi\Desktop\MBA_Xperiun_Data_ChallengeI\database\customers.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Cabeçalhos Promovidos",{"customer_city", "customer_state"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"customer_zip_code_prefix"}, dim_geolocation, {"geolocation_zip_code_prefix"}, "dim_geolocation", JoinKind.LeftOuter),
				    #"Expanded dim_geolocation" = Table.ExpandTableColumn(#"Merged Queries", "dim_geolocation", {"geolocation_lat", "geolocation_lng", "geolocation_city", "geolocation_state"}, {"geolocation_lat", "geolocation_lng", "geolocation_city", "geolocation_state"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded dim_geolocation",{{"geolocation_lat", type number}, {"geolocation_lng", type number}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Changed Type"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Duplicatas Removidas",{{"customer_zip_code_prefix", type text}, {"geolocation_lat", type text}, {"geolocation_lng", type text}}),
				    #"Dividir Coluna pela Posição" = Table.SplitColumn(#"Tipo Alterado1", "customer_zip_code_prefix", Splitter.SplitTextByPositions({0, 4}, false), {"customer_zip_code_prefix.1", "customer_zip_code_prefix.2"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Dividir Coluna pela Posição",{{"customer_zip_code_prefix.1", Int64.Type}, {"customer_zip_code_prefix.2", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado2",{"customer_zip_code_prefix.2"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"customer_zip_code_prefix.1", "customer_zip_code_prefix"}}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"customer_zip_code_prefix", type text}})
				in
				    #"Tipo Alterado3"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

