table dim_customers
	lineageTag: 4a781a2d-9acc-4a36-b5b0-2170f221762b

	column customer_id
		dataType: string
		lineageTag: d170cea4-c5bb-40df-a849-3c67ed58c3fb
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: df4ba0d0-ceee-45a6-90eb-0f82737f1ebe
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: string
		lineageTag: 86853a96-8c21-4166-8c51-d8bbdfc68cb9
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column Cliente = "Cliente" &" - "& RIGHT([customer_id], 8)
		lineageTag: 9da3ce3b-bdb2-42b2-9880-03a7dba668ae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column geolocation_zip_code_prefix
		dataType: string
		lineageTag: 4047635b-d65b-4923-9f45-6c5893c7ce43
		summarizeBy: none
		sourceColumn: geolocation_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column geolocation_city
		dataType: string
		lineageTag: 20a4c982-d50d-46a5-b66f-d501c77d9138
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: d349c87d-a477-40dd-b145-011fafa84d8d
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	column CEP
		dataType: string
		lineageTag: e0954247-0a0e-4c97-b8a7-a1ed259d77f9
		summarizeBy: none
		sourceColumn: CEP

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Fonte = Csv.Document(File.Contents(Source & "customers.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", type text}, {"customer_city", type text}, {"customer_state", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Tipo Alterado",{"customer_city", "customer_state"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"customer_zip_code_prefix"}, dim_geolocation, {"geolocation_zip_code_prefix"}, "dim_geolocation", JoinKind.LeftOuter),
				    #"Expanded dim_geolocation" = Table.ExpandTableColumn(#"Merged Queries", "dim_geolocation", {"geolocation_zip_code_prefix", "geolocation_city", "geolocation_state", "CEP"}, {"geolocation_zip_code_prefix", "geolocation_city", "geolocation_state", "CEP"})
				in
				    #"Expanded dim_geolocation"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

